version: '3.8'

services:
  app:
    build:
      context: .
    container_name: logistics-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      LOGISTICS_API_KEY: ${LOGISTICS_API_KEY:-haulmer-2025-apikey}
    command: ["php-fpm"]

  nginx:
    image: nginx:1.27-alpine
    container_name: logistics-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
